import type { Encounter } from './types';

export const encounters: Encounter[] = [
  // MUSHROOM ENCOUNTERS (7)
  {
    id: 1,
    biome: 'Temperate Forest',
    description: 'You stumble through thick undergrowth. Your stomach growls. You spot two things growing near a fallen log.',
    optionA: {
      name: 'Chanterelle Mushroom',
      emoji: '🍄',
      accentColor: '#f4a523',
      description: 'Golden-yellow, funnel-shaped with false gills running down the stem. Smells faintly of apricots.',
      fact: 'Chanterelles are prized edible mushrooms found worldwide. Their false gills (ridges, not blades) distinguish them from toxic lookalikes.',
      effects: { hunger: 25, health: 5, hydration: 0, clarity: 0 },
      outcome: 'The earthy, peppery flavor fills you with warmth. Good choice — chanterelles are one of nature\'s finest gifts.',
      safe: true,
    },
    optionB: {
      name: 'Jack-O-Lantern Mushroom',
      emoji: '🍄',
      accentColor: '#e8651a',
      description: 'Bright orange, fan-shaped caps growing in a dense cluster. True blade-like gills visible underneath.',
      fact: 'Omphalotus olearius causes severe cramps, vomiting, and diarrhea. They glow faintly in the dark (bioluminescence) — beautiful but brutal.',
      effects: { hunger: 10, health: -35, hydration: -15, clarity: -20 },
      outcome: 'Within an hour, violent cramps tear through your gut. You spend the night in agony, vomiting and shaking.',
      safe: false,
    },
  },
  {
    id: 2,
    biome: 'Mossy Clearing',
    description: 'Rain falls softly. In the damp earth, two fungi emerge from the moss.',
    optionA: {
      name: 'Destroying Angel',
      emoji: '🍄',
      accentColor: '#f0ede4',
      description: 'Pristine white cap, white gills, elegant white stem with a delicate skirt-like ring. Beautiful.',
      fact: 'Amanita virosa is responsible for most fatal mushroom poisonings worldwide. Symptoms are delayed 6-12 hours, then cause irreversible liver failure.',
      effects: { hunger: 15, health: -80, hydration: 0, clarity: -30 },
      outcome: 'It tastes… pleasant. But 8 hours later, your organs begin to shut down. The Destroying Angel earned its name.',
      safe: false,
    },
    optionB: {
      name: 'Puffball Mushroom',
      emoji: '🍄',
      accentColor: '#e8dcc8',
      description: 'Round, white, no visible stem or gills. Firm when squeezed. Pure white flesh inside when cut open.',
      fact: 'Calvatia gigantea (giant puffball) is safely edible when the interior is pure white. If it shows any yellow, green, or has a visible outline inside, discard it.',
      effects: { hunger: 30, health: 5, hydration: 5, clarity: 0 },
      outcome: 'Sliced and eaten raw, it\'s mild and filling. Puffballs are one of the easiest safe mushrooms to identify. Well done.',
      safe: true,
    },
  },
  {
    id: 3,
    biome: 'Old Growth Forest',
    description: 'Deep in ancient forest. Two mushrooms grow on a massive dead oak.',
    optionA: {
      name: 'Chicken of the Woods',
      emoji: '🍄',
      accentColor: '#ff8c42',
      description: 'Bright orange and yellow shelf-like brackets growing in overlapping fans on the trunk. No gills.',
      fact: 'Laetiporus sulphureus has a taste and texture remarkably similar to chicken. It\'s one of the "foolproof four" — beginner-safe wild mushrooms.',
      effects: { hunger: 35, health: 10, hydration: 5, clarity: 5 },
      outcome: 'Incredible. The meaty texture and savory flavor rival any chicken you\'ve ever had. A survival feast.',
      safe: true,
    },
    optionB: {
      name: 'Funeral Bell',
      emoji: '🍄',
      accentColor: '#8b6914',
      description: 'Small brown caps on thin stems growing in clusters on dead wood. A faint ring on the stem.',
      fact: 'Galerina marginata contains the same amatoxins as the Death Cap. Despite its small size, a handful can cause fatal liver damage.',
      effects: { hunger: 5, health: -70, hydration: 0, clarity: -35 },
      outcome: 'They looked so innocent. But amatoxins are already destroying your liver. The Funeral Bell tolls for you.',
      safe: false,
    },
  },
  {
    id: 4,
    biome: 'Birch Grove',
    description: 'Papery white bark surrounds you. At the base of two trees, mushrooms fruit from the soil.',
    optionA: {
      name: 'Fly Agaric',
      emoji: '🍄',
      accentColor: '#d42a2a',
      description: 'Iconic bright red cap covered in white raised spots. Thick white stem with a bulbous base wrapped in a scaly cup.',
      fact: 'Amanita muscaria contains ibotenic acid and muscimol. While rarely fatal, it causes delirium, nausea, and vivid hallucinations lasting 6-8 hours.',
      effects: { hunger: 10, health: -20, hydration: -5, clarity: -55 },
      outcome: 'The world fractures into kaleidoscope patterns. You lose hours. When you come to, you can barely remember your own name.',
      safe: false,
    },
    optionB: {
      name: 'Birch Bolete',
      emoji: '🍄',
      accentColor: '#8b6b4a',
      description: 'Brown domed cap with a spongy pore surface underneath instead of gills. Thick stem with faint dark scales.',
      fact: 'Leccinum scabrum is a reliable edible found under birch trees. The sponge-like pores (not gills) and scaly stem are key identifiers.',
      effects: { hunger: 25, health: 5, hydration: 5, clarity: 0 },
      outcome: 'Nutty and satisfying. The thick flesh fills your stomach. Foragers have prized these for centuries.',
      safe: true,
    },
  },
  {
    id: 5,
    biome: 'Shaded Ravine',
    description: 'A cool, damp ravine. Two different mushrooms peek from the leaf litter on the slope.',
    optionA: {
      name: 'Morel Mushroom',
      emoji: '🍄',
      accentColor: '#a08050',
      description: 'Honeycomb-patterned cap with deep pits and ridges. Completely hollow inside when sliced in half, from cap to stem.',
      fact: 'Morchella species are among the most prized wild mushrooms. The hollow interior when halved is the critical test — false morels are solid or cottony inside.',
      effects: { hunger: 30, health: 10, hydration: 0, clarity: 5 },
      outcome: 'The rich, meaty umami flavor is extraordinary. This is what chefs pay fifty dollars a pound for. You found it for free.',
      safe: true,
    },
    optionB: {
      name: 'False Morel',
      emoji: '🍄',
      accentColor: '#8b4513',
      description: 'Brain-like, wrinkled, lobed cap — irregular rather than honeycombed. Inside is chambered and cottony, not cleanly hollow.',
      fact: 'Gyromitra esculenta contains gyromitrin, which metabolizes into monomethylhydrazine (rocket fuel). It causes liver failure and can be fatal.',
      effects: { hunger: 10, health: -55, hydration: 0, clarity: -20 },
      outcome: 'Cramps strike within hours. Your liver screams. You just ate something that metabolizes into rocket fuel propellant.',
      safe: false,
    },
  },
  {
    id: 6,
    biome: 'Decaying Stump',
    description: 'A massive rotting stump hosts two colonies of fungi, fighting for territory.',
    optionA: {
      name: 'Oyster Mushroom',
      emoji: '🍄',
      accentColor: '#c8bda8',
      description: 'Soft, fan-shaped white-to-gray caps growing in overlapping shelves. Short off-center stems. Gills run down the stub of the stem. Mild anise scent.',
      fact: 'Pleurotus ostreatus is one of the most widely cultivated mushrooms in the world. It\'s also one of the few carnivorous fungi — it traps and digests nematode worms.',
      effects: { hunger: 25, health: 10, hydration: 5, clarity: 5 },
      outcome: 'Delicate and savory. The silky texture practically melts. Oyster mushrooms are a gift from the forest.',
      safe: true,
    },
    optionB: {
      name: 'Angel Wing',
      emoji: '🍄',
      accentColor: '#f0ebe0',
      description: 'Paper-thin, pure white fan-shaped caps. No stem at all — attached directly to wood. Almost translucent at the edges.',
      fact: 'Pleurocybella porrigens was long considered edible until 2004, when 59 people in Japan were poisoned and 17 died. It contains a compound toxic to the kidneys and brain.',
      effects: { hunger: 10, health: -45, hydration: 0, clarity: -30 },
      outcome: 'So thin and delicate it seemed harmless. Days later, your kidneys begin to fail. Beauty can be lethal.',
      safe: false,
    },
  },
  {
    id: 7,
    biome: 'Meadow Edge',
    description: 'Where forest meets grassland, two mushrooms grow in the dewy morning grass.',
    optionA: {
      name: 'Death Cap',
      emoji: '🍄',
      accentColor: '#a8b060',
      description: 'Pale greenish-yellow cap, white gills that don\'t attach to the stem. A saclike cup (volva) wraps the base hidden in soil. Faint honey smell.',
      fact: 'Amanita phalloides causes over 90% of mushroom-related deaths worldwide. One cap contains enough amatoxin to kill an adult. Symptoms appear 6-12 hours after ingestion.',
      effects: { hunger: 15, health: -90, hydration: 0, clarity: -20 },
      outcome: 'It tasted fine. That\'s the cruelest part. By the time symptoms appear tomorrow, your liver will already be destroyed.',
      safe: false,
    },
    optionB: {
      name: 'Meadow Mushroom',
      emoji: '🍄',
      accentColor: '#e8ddd0',
      description: 'White cap with pink gills that darken to chocolate brown as it ages. No cup at the base — stem sits clean in the soil. Smells like fresh mushrooms.',
      fact: 'Agaricus campestris is the wild ancestor of the common button mushroom. Pink-to-brown gills and NO volva (cup) at the base distinguish it from deadly Amanitas.',
      effects: { hunger: 25, health: 5, hydration: 0, clarity: 5 },
      outcome: 'The familiar mushroom flavor steadies your nerves. This is essentially the same species sold in every grocery store.',
      safe: true,
    },
  },

  // PLANT ENCOUNTERS (7)
  {
    id: 8,
    biome: 'Streamside',
    description: 'You find a trickling stream. Along its banks, two plants catch your eye.',
    optionA: {
      name: 'Watercress',
      emoji: '🌿',
      accentColor: '#4a9e3f',
      description: 'Small, round dark-green leaves growing in shallow running water. Peppery smell when crushed.',
      fact: 'Nasturtium officinale is a nutrient-dense aquatic plant rich in vitamins A, C, and K. It\'s been foraged for thousands of years.',
      effects: { hunger: 15, health: 10, hydration: 20, clarity: 5 },
      outcome: 'The peppery bite is refreshing. The watercress hydrates you and settles your stomach. A wise choice.',
      safe: true,
    },
    optionB: {
      name: 'Water Hemlock',
      emoji: '🌿',
      accentColor: '#5db85d',
      description: 'Tall stems with clusters of tiny white flowers. Hollow, chambered stem with a faint carrot-like smell.',
      fact: 'Cicuta is considered the most toxic plant in North America. Its toxin cicutoxin causes violent seizures and death, sometimes within 30 minutes.',
      effects: { hunger: 5, health: -60, hydration: 0, clarity: -40 },
      outcome: 'Your vision blurs. Muscles lock. Violent convulsions wrack your body. This was the deadliest plant in North America.',
      safe: false,
    },
  },
  {
    id: 9,
    biome: 'Rocky Hillside',
    description: 'You\'re weakening. On a sun-warmed slope, two plants grow from the cracks.',
    optionA: {
      name: 'Wild Garlic',
      emoji: '🌱',
      accentColor: '#6b8e4e',
      description: 'Broad, smooth green leaves rising from the ground. Strong garlic smell when a leaf is torn.',
      fact: 'Allium ursinum is safe and nutritious. The KEY identifier is the garlic smell — its deadly lookalike, Lily of the Valley, has no smell.',
      effects: { hunger: 20, health: 15, hydration: 5, clarity: 10 },
      outcome: 'The familiar garlic tang is unmistakable. It warms your core and the antimicrobial properties help fight infection.',
      safe: true,
    },
    optionB: {
      name: 'Lily of the Valley',
      emoji: '🌱',
      accentColor: '#7aad6b',
      description: 'Similar broad green leaves, but growing in pairs from the stem. No smell when torn. Tiny white bell flowers.',
      fact: 'Convallaria majalis contains cardiac glycosides that disrupt heart rhythm. Every part is toxic. Even the water in a vase of these flowers can be lethal.',
      effects: { hunger: 5, health: -50, hydration: 0, clarity: -25 },
      outcome: 'Your heart begins to race, then stutter. Nausea overwhelms you. Cardiac glycosides are attacking your heart muscle.',
      safe: false,
    },
  },
  {
    id: 10,
    biome: 'Overgrown Trail',
    description: 'The trail is choked with tall plants. Two umbrella-shaped flower clusters block your path.',
    optionA: {
      name: 'Wild Carrot (Queen Anne\'s Lace)',
      emoji: '🌸',
      accentColor: '#e8e0d0',
      description: 'Flat-topped cluster of tiny white flowers with a single tiny dark purple flower in the center. Hairy stem. Smells like carrot when root is pulled.',
      fact: 'Daucus carota is the wild ancestor of the domestic carrot. The single purple floret in the center and hairy stem distinguish it from deadly poison hemlock.',
      effects: { hunger: 20, health: 5, hydration: 10, clarity: 5 },
      outcome: 'The root is tough but unmistakably carrot-flavored. Energy trickles back. The ancestor of every carrot you\'ve ever eaten.',
      safe: true,
    },
    optionB: {
      name: 'Poison Hemlock',
      emoji: '🌸',
      accentColor: '#d0dcc0',
      description: 'Similar umbrella-shaped white flower clusters, but the smooth stem is marked with irregular reddish-purple blotches. No purple center flower. Musty smell.',
      fact: 'Conium maculatum killed Socrates. Its alkaloid coniine causes ascending paralysis — you stay conscious as your body shuts down from the feet up.',
      effects: { hunger: 5, health: -65, hydration: 0, clarity: -30 },
      outcome: 'Numbness creeps up from your feet. Your legs stop responding. Then your chest. You stay horribly aware the entire time.',
      safe: false,
    },
  },
  {
    id: 11,
    biome: 'Sunny Clearing',
    description: 'Warm sunlight floods a gap in the canopy. Two leafy plants bask in the light.',
    optionA: {
      name: 'Stinging Nettle',
      emoji: '🌿',
      accentColor: '#4a7a35',
      description: 'Serrated, pointed leaves covered in tiny translucent hair-like needles. Opposite leaf pairs climbing a square stem.',
      fact: 'Urtica dioica stings on contact but is highly nutritious when cooked. Rich in iron, calcium, and protein. It\'s been used as food and medicine for over 3,000 years.',
      effects: { hunger: 20, health: 15, hydration: 10, clarity: 5 },
      outcome: 'Your fingers sting as you harvest, but once bruised and eaten, the leaves are rich and spinach-like. Worth the pain.',
      safe: true,
    },
    optionB: {
      name: 'Giant Hogweed',
      emoji: '🌿',
      accentColor: '#6b9a50',
      description: 'Massive plant — leaves up to 5 feet wide. Thick stem with dark reddish-purple blotches and coarse white bristles.',
      fact: 'Heracleum mantegazzianum sap causes phytophotodermatitis — severe chemical burns activated by sunlight. Blisters can take months to heal and leave permanent scars.',
      effects: { hunger: 5, health: -40, hydration: -10, clarity: -15 },
      outcome: 'The sap burns everywhere it touches. In the sunlight, your skin erupts in massive blisters. The pain is blinding.',
      safe: false,
    },
  },
  {
    id: 12,
    biome: 'Ditch Bank',
    description: 'A drainage ditch runs through the landscape. Two plants grow thick along its muddy edge.',
    optionA: {
      name: 'Cattail',
      emoji: '🌾',
      accentColor: '#8b7355',
      description: 'Tall grass-like plant with a distinctive brown cigar-shaped spike at the top. Flat, sword-shaped leaves. Growing in standing water.',
      fact: 'Typha latifolia is called the "supermarket of the swamp." Roots, shoots, pollen, and young flower heads are all edible. Indigenous peoples used every part of this plant.',
      effects: { hunger: 25, health: 5, hydration: 15, clarity: 5 },
      outcome: 'You peel the outer layers of the shoot and eat the tender white core. Mild, starchy, satisfying. The wilderness provides.',
      safe: true,
    },
    optionB: {
      name: 'Poison Iris',
      emoji: '🌾',
      accentColor: '#5a7a5a',
      description: 'Sword-shaped leaves very similar to the previous plant but in drier soil. Flattened in a fan pattern at the base. No brown spike — dried seed pods instead.',
      fact: 'Iris pseudacorus (yellow flag iris) contains irisin, a glycoside causing severe gastric distress. Its leaves are often confused with cattails by inexperienced foragers.',
      effects: { hunger: 5, health: -30, hydration: -10, clarity: -15 },
      outcome: 'The burning starts in your mouth and races to your stomach. Hours of cramping and vomiting follow. Those weren\'t cattails.',
      safe: false,
    },
  },
  {
    id: 13,
    biome: 'Forest Floor',
    description: 'The forest floor is carpeted in green. Two low-growing plants spread across the ground beneath the canopy.',
    optionA: {
      name: 'Wood Sorrel',
      emoji: '🍀',
      accentColor: '#5a9e45',
      description: 'Three heart-shaped leaflets folding from a central point like a clover. Small yellow five-petaled flowers. Leaves fold down at night.',
      fact: 'Oxalis species are edible with a pleasant lemony-sour taste due to oxalic acid. Safe in moderate amounts. Used by foragers worldwide as a trail snack.',
      effects: { hunger: 12, health: 5, hydration: 10, clarity: 10 },
      outcome: 'A burst of bright lemon flavor — refreshing and thirst-quenching. The sour tang sharpens your focus. Nature\'s lemonade.',
      safe: true,
    },
    optionB: {
      name: 'Spurge',
      emoji: '🍀',
      accentColor: '#6ba050',
      description: 'Low-growing rounded leaves in pairs. Snap the stem and thick milky-white sap oozes out immediately. Tiny inconspicuous flowers.',
      fact: 'Euphorbia species contain toxic latex that causes severe irritation to skin, eyes, and digestive tract. Even skin contact can cause blistering and temporary blindness.',
      effects: { hunger: 5, health: -25, hydration: -15, clarity: -20 },
      outcome: 'The milky sap burns your lips, then your throat, then your entire digestive tract. Your eyes water uncontrollably for hours.',
      safe: false,
    },
  },
  {
    id: 14,
    biome: 'Pine Forest',
    description: 'You\'re deep in a conifer forest. The air smells of resin. Two potential food sources catch your attention.',
    optionA: {
      name: 'Pine Bark & Needles',
      emoji: '🌲',
      accentColor: '#5a7a4a',
      description: 'The inner bark of a pine tree — a thin, moist white layer beneath the rough outer bark. Nearby needles are long, in clusters of two, with a citrus smell.',
      fact: 'Pine cambium (inner bark) was eaten by Indigenous peoples and Scandinavian settlers. Pine needle tea is rich in vitamin C. Scots pine, white pine, and ponderosa are all safe.',
      effects: { hunger: 15, health: 10, hydration: 5, clarity: 10 },
      outcome: 'Resinous and chewy, but the vitamin C hits your system immediately. Your gums stop bleeding. Scurvy won\'t take you today.',
      safe: true,
    },
    optionB: {
      name: 'Yew Needles',
      emoji: '🌲',
      accentColor: '#2a5a2a',
      description: 'Short, flat, dark green needles arranged in two rows on the twig. No citrus smell. The needles are softer and darker than the pine, with a bitter taste.',
      fact: 'Taxus baccata needles contain taxine alkaloids that interfere with the heart\'s electrical system. Historically used for poison arrows. Even small amounts can cause fatal cardiac arrest.',
      effects: { hunger: 5, health: -60, hydration: 0, clarity: -20 },
      outcome: 'Bitter. Wrong. Your heart begins to beat irregularly. Taxine alkaloids disrupt the electrical signals keeping you alive.',
      safe: false,
    },
  },

  // BERRY ENCOUNTERS (7)
  {
    id: 15,
    biome: 'Forest Edge',
    description: 'At the tree line you find berry bushes heavy with fruit. Two types hang within arm\'s reach.',
    optionA: {
      name: 'Wild Blackberries',
      emoji: '🫐',
      accentColor: '#2d1b4e',
      description: 'Deep purple-black clusters of small drupelets. Thorny canes. Sweet smell.',
      fact: 'Rubus fruticosus is one of the safest wild berries to forage. Aggregate berries (like blackberries and raspberries) are almost never toxic.',
      effects: { hunger: 20, health: 10, hydration: 15, clarity: 5 },
      outcome: 'Sweet, tart juice bursts in your mouth. Energy returns to your limbs. Nature\'s candy.',
      safe: true,
    },
    optionB: {
      name: 'Pokeweed Berries',
      emoji: '🫐',
      accentColor: '#4a1942',
      description: 'Dark purple berries in drooping clusters on thick reddish-purple stems. Slightly flattened shape.',
      fact: 'Phytolacca americana contains phytolaccatoxin. All parts are poisonous, especially roots and berries. Used historically as ink and dye, never as food.',
      effects: { hunger: 10, health: -30, hydration: -10, clarity: -15 },
      outcome: 'Burning spreads through your throat. Within hours, severe vomiting and bloody diarrhea leave you dangerously weak.',
      safe: false,
    },
  },
  {
    id: 16,
    biome: 'Hedgerow',
    description: 'A thick hedgerow lines an old field boundary. Two types of bright berries peek through the leaves.',
    optionA: {
      name: 'Hawthorn Berries',
      emoji: '🔴',
      accentColor: '#c0392b',
      description: 'Small, deep red oval berries in clusters. The bush has sharp thorns and small lobed leaves. Berries are firm with a single large seed.',
      fact: 'Crataegus berries have been used medicinally for centuries to support heart health. The mealy flesh is mildly sweet and safe to eat, though best cooked into jams.',
      effects: { hunger: 15, health: 15, hydration: 5, clarity: 5 },
      outcome: 'Mealy and mild, with a hint of apple flavor. The old herbalists called these "heart berries" for their medicinal properties.',
      safe: true,
    },
    optionB: {
      name: 'Yew Berries',
      emoji: '🔴',
      accentColor: '#d44040',
      description: 'Bright red berry-like structures, each with a fleshy cup surrounding a single seed visible at the opening. Flat, dark needle-like evergreen leaves.',
      fact: 'Taxus baccata — while the fleshy red aril is technically edible, the SEED inside and all other parts contain taxine alkaloids. Chewing even a few seeds can stop the heart.',
      effects: { hunger: 5, health: -70, hydration: 0, clarity: -20 },
      outcome: 'You bit into the seeds. Taxine alkaloids flood your bloodstream. Your heart rhythm destabilizes. There is no antidote.',
      safe: false,
    },
  },
  {
    id: 17,
    biome: 'Woodland Path',
    description: 'Walking beneath the canopy, two berry-laden shrubs compete for the dappled light.',
    optionA: {
      name: 'Bittersweet Nightshade',
      emoji: '🫐',
      accentColor: '#6a2c8a',
      description: 'Small oval berries ripening from green to yellow to bright red. Star-shaped purple flowers with yellow centers still on the vine. Pointed leaves.',
      fact: 'Solanum dulcamara contains solanine glycoalkaloids. While less toxic than deadly nightshade, ingesting berries causes vomiting, diarrhea, slowed heart rate, and paralysis.',
      effects: { hunger: 5, health: -35, hydration: -10, clarity: -25 },
      outcome: 'The berries taste bitter, then strangely sweet. Soon your heart slows. Weakness pulls you to the ground.',
      safe: false,
    },
    optionB: {
      name: 'Wild Rose Hips',
      emoji: '🫐',
      accentColor: '#d06030',
      description: 'Firm, round reddish-orange pods where flowers once bloomed. The bush has thorns and compound leaves with serrated leaflets. Faint floral scent.',
      fact: 'Rosa canina hips contain more vitamin C per gram than oranges. They\'ve been used as survival food for millennia and were issued to British children during WWII rationing.',
      effects: { hunger: 15, health: 15, hydration: 10, clarity: 10 },
      outcome: 'Tart and tangy. The vitamin C hits your system like a jolt of electricity. Your gums ache less. Color returns to the world.',
      safe: true,
    },
  },
  {
    id: 18,
    biome: 'Mountain Slope',
    description: 'At altitude, sparse vegetation clings to the rocky soil. Two small berry bushes grow in a sheltered nook.',
    optionA: {
      name: 'Bilberries',
      emoji: '🫐',
      accentColor: '#2a1a4a',
      description: 'Tiny dark blue-black berries growing singly on low bushes. Red-tinged flesh inside. Fine-toothed oval leaves on wiry stems.',
      fact: 'Vaccinium myrtillus is the European wild blueberry. RAF pilots in WWII reportedly ate bilberry jam to improve night vision. Extremely rich in anthocyanin antioxidants.',
      effects: { hunger: 15, health: 10, hydration: 10, clarity: 15 },
      outcome: 'Intensely sweet-tart, staining your fingers purple-black. Your vision sharpens. Your mind clears. A perfect find.',
      safe: true,
    },
    optionB: {
      name: 'Baneberry',
      emoji: '🫐',
      accentColor: '#e8e0e0',
      description: 'Glossy white berries with a single black dot on each — like tiny doll\'s eyes. Growing on a thick bright red stem. Jagged compound leaves.',
      fact: 'Actaea pachypoda (doll\'s eyes) contains cardiogenic toxins. As few as six berries can cause cardiac arrest in an adult. The name "baneberry" literally means "death berry."',
      effects: { hunger: 5, health: -60, hydration: 0, clarity: -30 },
      outcome: 'The tiny doll\'s eyes stare up at you as you eat them. Within minutes, your heart begins to stagger and fail.',
      safe: false,
    },
  },
  {
    id: 19,
    biome: 'Autumn Thicket',
    description: 'Late-season fruit hangs heavy in a dense thicket. Two shrubs offer their harvest.',
    optionA: {
      name: 'Elderberries',
      emoji: '🫐',
      accentColor: '#1a0a2a',
      description: 'Tiny dark purple-black berries in large flat-topped clusters. Compound leaves with 5-7 toothed leaflets. Woody stems.',
      fact: 'Sambucus nigra berries are safe when cooked but mildly toxic when raw (containing cyanogenic glycosides). Elderberry syrup and wine have been made for centuries.',
      effects: { hunger: 15, health: 5, hydration: 10, clarity: 0 },
      outcome: 'Slightly bitter raw, but you keep them down. A mild stomachache is the price. Cooked would have been better, but you\'ll survive.',
      safe: true,
    },
    optionB: {
      name: 'Privet Berries',
      emoji: '🫐',
      accentColor: '#0a0a1a',
      description: 'Shiny black berries in dense clusters. Smooth, glossy, untoothed opposite leaves. The berries look very similar to elderberries.',
      fact: 'Ligustrum vulgare berries contain ligustrin and syringin glycosides. Even a handful causes severe gastroenteritis, and larger doses affect the kidneys and cardiovascular system.',
      effects: { hunger: 5, health: -30, hydration: -15, clarity: -15 },
      outcome: 'They looked almost identical to the safe ones. Your gut violently disagrees with your choice. The difference was in the leaves.',
      safe: false,
    },
  },
  {
    id: 20,
    biome: 'River Crossing',
    description: 'Wading across a slow river, you spot two plants growing from the shallow water.',
    optionA: {
      name: 'Wild Rice',
      emoji: '🌾',
      accentColor: '#7a6a4a',
      description: 'Tall grass growing in shallow water, with drooping seed heads full of long, dark grains. Seeds scatter when the stalk is shaken.',
      fact: 'Zizania aquatica has been a staple food of Great Lakes Indigenous peoples for thousands of years. The seeds are highly nutritious and can be eaten raw or parched.',
      effects: { hunger: 30, health: 10, hydration: 5, clarity: 10 },
      outcome: 'The nutty, earthy grains are incredibly satisfying. Real carbohydrates. Real energy. You feel almost human again.',
      safe: true,
    },
    optionB: {
      name: 'Water Arum',
      emoji: '🌾',
      accentColor: '#4a7a3a',
      description: 'Glossy, arrow-shaped leaves rising from the water. A white petal-like sheath wraps around a fleshy central spike. Red berries in a tight cluster.',
      fact: 'Calla palustris contains calcium oxalate crystals that shred mouth and throat tissue at a microscopic level. The burning is immediate and can cause airway swelling.',
      effects: { hunger: 5, health: -35, hydration: -10, clarity: -20 },
      outcome: 'Microscopic needles of calcium oxalate embed in your tongue and throat. The burning is indescribable. Your airway begins to swell.',
      safe: false,
    },
  },
  {
    id: 21,
    biome: 'Desert Wash',
    description: 'The dry streambed is sparse but not lifeless. Two plants have stored water against the drought.',
    optionA: {
      name: 'Prickly Pear Cactus',
      emoji: '🌵',
      accentColor: '#4a8a3a',
      description: 'Flat, oval green pads covered in clusters of fine hair-like spines and larger barbed spines. Purple-red fruit at the pad edges. The pads ooze green when cut.',
      fact: 'Opuntia fruit (tunas) and pads (nopales) have been eaten in the Americas for 9,000 years. De-spine the fruit, eat the sweet pulp. The pads are a vegetable staple in Mexico.',
      effects: { hunger: 20, health: 5, hydration: 25, clarity: 5 },
      outcome: 'The sweet, watermelon-like fruit quenches your desperate thirst. Hydration, sugar, and vitamins in one spiny package.',
      safe: true,
    },
    optionB: {
      name: 'Pencil Cactus',
      emoji: '🌵',
      accentColor: '#6a9a4a',
      description: 'Thin, green, pencil-like succulent stems branching in all directions. No visible spines. Oozes thick milky-white sap when broken.',
      fact: 'Euphorbia tirucalli latex causes severe chemical burns to eyes and skin, and extreme gastric distress if ingested. Even fumes from burning it can cause temporary blindness.',
      effects: { hunger: 5, health: -40, hydration: -15, clarity: -30 },
      outcome: 'The milky sap is caustic acid. Your mouth blisters instantly. Your eyes stream with tears. The desert just punished you.',
      safe: false,
    },
  },

  // ANIMAL & INSECT ENCOUNTERS (5)
  {
    id: 22,
    biome: 'Dense Undergrowth',
    description: 'Deep in the forest, light barely filters through. Two creatures present themselves as potential food.',
    optionA: {
      name: 'Banana Slug',
      emoji: '🐛',
      accentColor: '#c4a834',
      description: 'A large, bright yellow slug leaving a slime trail across a rotting log. About 8 inches long.',
      fact: 'Banana slugs (Ariolimax columbianus) are technically edible but the slime numbs your mouth. Indigenous peoples occasionally used them. Best cooked to reduce slime.',
      effects: { hunger: 15, health: -5, hydration: 5, clarity: -5 },
      outcome: 'You gag on the slime, but get it down. Your mouth goes numb for hours. Not pleasant, but you\'ll live.',
      safe: true,
    },
    optionB: {
      name: 'Rough-skinned Newt',
      emoji: '🦎',
      accentColor: '#8b5e3c',
      description: 'Small brown salamander-like creature with a bright orange belly. Moves slowly, seemingly unafraid.',
      fact: 'Taricha granulosa carries tetrodotoxin (the same as puffer fish) in its skin — enough to kill several adult humans. Its bold coloring is a warning.',
      effects: { hunger: 10, health: -90, hydration: 0, clarity: -50 },
      outcome: 'The bright orange belly was a warning you ignored. Tetrodotoxin paralyzes your muscles. You can\'t breathe.',
      safe: false,
    },
  },
  {
    id: 23,
    biome: 'Rocky Stream',
    description: 'Wading in a cold stream, you spot two creatures that could become a meal.',
    optionA: {
      name: 'Crayfish',
      emoji: '🦀',
      accentColor: '#b85c3a',
      description: 'A small lobster-like creature with pincers, hiding beneath a flat rock in the stream. About 4 inches long. Olive-brown shell.',
      fact: 'Freshwater crayfish are excellent survival food found on every continent except Africa and Antarctica. High in protein. Always cook to kill parasites.',
      effects: { hunger: 30, health: 10, hydration: 5, clarity: 5 },
      outcome: 'You crack the tail and eat the sweet, lobster-like meat. Real protein at last. Your body sings with gratitude.',
      safe: true,
    },
    optionB: {
      name: 'Cane Toad',
      emoji: '🐸',
      accentColor: '#8b7355',
      description: 'A large, warty toad sitting boldly on a streamside rock. Prominent bulging glands behind each eye. Dry, leathery brown skin.',
      fact: 'Rhinella marina secretes bufotoxin from parotoid glands behind its eyes. The toxin affects the heart and can be lethal. Even dogs die from mouthing cane toads.',
      effects: { hunger: 10, health: -55, hydration: 0, clarity: -30 },
      outcome: 'The glands behind its eyes were poison factories. Bufotoxin crashes through your nervous system. Your heart stutters dangerously.',
      safe: false,
    },
  },
  {
    id: 24,
    biome: 'Rotting Log',
    description: 'You pry open a rotting log. Two types of larvae squirm in the exposed wood.',
    optionA: {
      name: 'Beetle Grubs',
      emoji: '🐛',
      accentColor: '#e8dcc0',
      description: 'Fat, C-shaped white grubs with brown heads. About thumb-sized. Soft bodies curled in the rotting wood. No distinct markings.',
      fact: 'Wood-boring beetle larvae (like longhorn grubs) are eaten across Southeast Asia, Africa, and South America. High in fat and protein — a genuine survival superfood.',
      effects: { hunger: 25, health: 5, hydration: 5, clarity: 0 },
      outcome: 'You close your eyes and bite down. Creamy, nutty, surprisingly inoffensive. Protein floods your starving muscles.',
      safe: true,
    },
    optionB: {
      name: 'Brightly Banded Caterpillar',
      emoji: '🐛',
      accentColor: '#e8a030',
      description: 'Fuzzy caterpillar with bold bands of orange, black, and white. Long branching spines protruding from each segment. Curls defensively when touched.',
      fact: 'Many brightly colored and spiny caterpillars contain venomous spines or sequester plant toxins. Bold warning coloration in larvae almost always signals danger.',
      effects: { hunger: 5, health: -35, hydration: -5, clarity: -25 },
      outcome: 'The spines inject venom as you try to swallow. Your throat swells. Searing pain radiates through your mouth and esophagus.',
      safe: false,
    },
  },
  {
    id: 25,
    biome: 'Pond Edge',
    description: 'A still pond gleams in the afternoon light. Two potential food sources present themselves at the muddy edge.',
    optionA: {
      name: 'Freshwater Mussels',
      emoji: '🐚',
      accentColor: '#5a6a5a',
      description: 'Dark oval shells half-buried in the mud at the pond\'s edge. Shells slightly open, filtering water. Tough to pry apart.',
      fact: 'Freshwater mussels are edible and were a major food source for Indigenous peoples. They\'re tougher and less flavorful than saltwater relatives but safe and protein-rich.',
      effects: { hunger: 20, health: 5, hydration: 10, clarity: 0 },
      outcome: 'Tough and chewy, but unmistakably nutritious. The mineral-rich flesh fuels your aching body. Survival isn\'t about taste.',
      safe: true,
    },
    optionB: {
      name: 'Brightly Colored Frog',
      emoji: '🐸',
      accentColor: '#2589e8',
      description: 'A tiny frog, barely an inch long, with vivid electric blue skin and black spots. Sitting openly on a leaf, making no attempt to hide.',
      fact: 'Dendrobatidae (poison dart frogs) advertise their lethality with bright colors. Some species carry enough batrachotoxin to kill 10 adult humans through skin contact alone.',
      effects: { hunger: 5, health: -80, hydration: 0, clarity: -40 },
      outcome: 'A creature that small, that bright, that unafraid — it was screaming "don\'t touch me." Batrachotoxin shuts down your nervous system.',
      safe: false,
    },
  },
  {
    id: 26,
    biome: 'Sandy Bank',
    description: 'A sandy riverbank bakes in the sun. Two creatures bask in the warmth.',
    optionA: {
      name: 'Large Brown Cricket',
      emoji: '🦗',
      accentColor: '#6b5a3c',
      description: 'A plump field cricket, dull brown, about an inch long. Strong back legs. Hiding under a warm stone. No bright colors.',
      fact: 'Gryllidae (field crickets) are one of the most widely eaten insects globally. Over 2 billion people regularly consume insects. Crickets are 65% protein by dry weight.',
      effects: { hunger: 15, health: 5, hydration: 0, clarity: 5 },
      outcome: 'Crunchy, nutty, and surprisingly palatable. Two billion people can\'t be wrong. Pure protein in a tiny package.',
      safe: true,
    },
    optionB: {
      name: 'Glossy Black Beetle',
      emoji: '🪲',
      accentColor: '#1a1a2a',
      description: 'A large, shiny black beetle with a narrow waist. When disturbed, it raises its tail end high in the air in a defensive posture. Strong chemical smell.',
      fact: 'Blister beetles (Meloidae family) contain cantharidin, one of the most toxic substances per body weight in the insect world. Even handling can cause severe skin blisters.',
      effects: { hunger: 5, health: -40, hydration: -5, clarity: -20 },
      outcome: 'Cantharidin burns through your mouth, throat, and stomach lining. Blisters erupt wherever the chemical touches. A devastating mistake.',
      safe: false,
    },
  },

  // AQUATIC / COASTAL ENCOUNTERS (3)
  {
    id: 27,
    biome: 'Tidal Pool',
    description: 'Low tide exposes shallow pools among the rocks. Two marine creatures wait in the trapped water.',
    optionA: {
      name: 'Common Limpet',
      emoji: '🐚',
      accentColor: '#8a8a7a',
      description: 'Cone-shaped shells clinging tightly to rocks. Rough, ridged exterior. About the size of a coin. Pried off to reveal a muscular foot.',
      fact: 'Patella vulgata has been a coastal survival food since prehistoric times. Tough and chewy but safe and nutritious. Found on rocky shores worldwide.',
      effects: { hunger: 15, health: 5, hydration: 5, clarity: 5 },
      outcome: 'Chewy as rubber, salty as the sea, but your body craves the minerals. Coastal peoples have survived on these for millennia.',
      safe: true,
    },
    optionB: {
      name: 'Blue-ringed Creature',
      emoji: '🐙',
      accentColor: '#d4a820',
      description: 'A tiny octopus, barely 5 inches, resting in the pool. Yellowish body with iridescent blue rings that pulse and glow when it moves.',
      fact: 'Hapalochlaena (blue-ringed octopus) carries enough tetrodotoxin to kill 26 adults. There is no antivenom. The painless bite means victims often don\'t realize they\'ve been envenomated.',
      effects: { hunger: 5, health: -95, hydration: 0, clarity: -40 },
      outcome: 'You barely felt the bite as you grabbed it. The blue rings flashed brilliantly — a final warning. Paralysis comes in minutes.',
      safe: false,
    },
  },
  {
    id: 28,
    biome: 'Kelp Beach',
    description: 'Storm wrack litters the beach. Two types of seaweed have washed ashore, still fresh.',
    optionA: {
      name: 'Sea Lettuce',
      emoji: '🌿',
      accentColor: '#3a8a3a',
      description: 'Thin, bright green translucent sheets of seaweed. Ruffled edges. Soft and pliable. No strong smell — just clean ocean.',
      fact: 'Ulva lactuca is eaten worldwide in soups, salads, and dried snacks. It\'s rich in iron, protein, and vitamins A and C. One of the most common edible seaweeds globally.',
      effects: { hunger: 12, health: 10, hydration: 15, clarity: 10 },
      outcome: 'Salty, green, and refreshing. The ocean\'s salad. Minerals and vitamins flood your depleted system.',
      safe: true,
    },
    optionB: {
      name: 'Dull Green Algae Mat',
      emoji: '🌿',
      accentColor: '#4a6a3a',
      description: 'A thick, slimy blue-green mat of algae from a freshwater runoff area on the beach. Musty, unpleasant earthy smell. Coats the rocks in slick layers.',
      fact: 'Cyanobacteria (blue-green algae) blooms produce microcystins and other hepatotoxins that cause liver damage, neurological symptoms, and potentially death. Never eat algae from still water.',
      effects: { hunger: 5, health: -45, hydration: -10, clarity: -30 },
      outcome: 'The musty taste should have stopped you. Microcystins attack your liver within hours. The slimy texture haunts your fading consciousness.',
      safe: false,
    },
  },
  {
    id: 29,
    biome: 'Mangrove Swamp',
    description: 'Ankle-deep in warm tidal water, tangled roots surround you. Two food possibilities emerge from the murk.',
    optionA: {
      name: 'Mangrove Periwinkle',
      emoji: '🐚',
      accentColor: '#6a6a5a',
      description: 'Small spiral-shelled snails clinging to the mangrove roots, just above the waterline. Dozens clustered together. Operculum seals the opening.',
      fact: 'Littorina species are eaten throughout tropical coasts. Boiling them briefly makes extraction easy. They\'ve been a protein source for coastal peoples on every tropical continent.',
      effects: { hunger: 20, health: 5, hydration: 5, clarity: 5 },
      outcome: 'Tiny but numerous. You boil a handful and pick out the meat. Salty, briny protein. The mangrove provides.',
      safe: true,
    },
    optionB: {
      name: 'Cone Snail',
      emoji: '🐚',
      accentColor: '#c8a870',
      description: 'A beautiful cone-shaped shell with intricate brown-and-white patterns. Partially buried in sand. A fleshy siphon protrudes from the narrow end.',
      fact: 'Conus geographus fires a venomous harpoon-like tooth containing conotoxins — a cocktail of hundreds of different paralyzing compounds. Called the "cigarette snail" because you have time for one last smoke.',
      effects: { hunger: 5, health: -85, hydration: 0, clarity: -35 },
      outcome: 'A barbed harpoon fires from the shell and pierces your finger. The beautiful pattern was the last beautiful thing you noticed clearly.',
      safe: false,
    },
  },
];

export const ENCOUNTERS_PER_RUN = 7;
export const TOTAL_ENCOUNTERS = encounters.length;
